# Generated by Django 4.1.1 on 2022-09-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitycampus',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
