# Generated by Django 4.1.1 on 2022-09-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0002_alter_universitycampus_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycampus',
            old_name='campus_ID',
            new_name='campus_id',
        ),
    ]
